[build]
builder = "NIXPACKS"
buildCommand = "pip3 install -r pagcor_bot/requirements.txt"

[deploy]
startCommand = "python3 pagcor_bot/bot.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3